name: Certinfo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: atsign-company/certinfo-action@v1

      - name: Get certinfo for root server
        run: certinfo root.atsign.org:64
